### ISSUE TITLE
Secret key in source code

### ISSUE THREAD

**Issue by icecreammatt** [eggytronixx/media-streaming-player#1]
http://www.devfactor.net/2014/12/30/2375-amazon-mistake/

I know it isn't an EC2 key, but you probably should not put your actual secret key in your source code. Bots scrape Github for those sorts of things. What I would do instead is create a `soundcloud.sample.js` file that contains all the same code but with a place holder key and then instruct users to rename the file in the instructions.

Alternatively a more clean way would be to store the keys in an environmental variable you export before running the app.

`$ export SOUND_CLOUD_KEY=<TOKEN_HERE>`

Then in node you could use `process.env.SOUND_CLOUD_KEY` to access the key.

https://nodejs.org/api/process.html#process_process_env

Cool project though :+1:

**Comment by eggytronixx** [comment]
Oh man I didn't notice that. Thanks for the heads up
